# Generated by Django 2.2.3 on 2019-09-13 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chip',
            old_name='breed',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='chip',
            old_name='release',
            new_name='rating',
        ),
    ]
